site_name: RedisBloom Documentation
site_url: http://redisbloom.io
repo_url: https://github.com/RedisLabsModules/RedisBloom
repo_name: RedisLabsModules/RedisBloom

google_analytics:
  - 'UA-92003007-1'
  - 'auto'
  
use_directory_urls: true

theme:
  name: 'material'
  language: 'en'
  logo: 'logo.png'
  favicon: 'favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false
  
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
 
pages:
    - 'ReBloom': 'index.md'
    - 'Quick Start': 'Quick_Start.md'
    - 'Bloom Commands': 'Bloom_Commands.md'
    - 'Cuckoo Filter Commands': 'Cuckoo_Commands.md'
    - 'Java API': 'Java_Client.md'
    - 'Contributor agreement': 'contrib.md'

