site_name: ReBloom Documentation
repo_url: https://github.com/RedisLabsModules/rebloom
theme: material

google_analytics:
  - 'UA-92003007-8'
  - 'auto'
markdown_extensions:
  - codehilite
  - toc(permalink=true)
 
pages:
    - 'ReBloom': 'index.md'
    - 'Quick Start': 'Quick_Start.md'
    - 'Bloom Commands': 'Bloom_Commands.md'
    - 'Cuckoo Filter Commands': 'Cuckoo_Commands.md'
    - 'Java API': 'Java_Client.md' 
