name: CI Full suite
# This is a full workflow for the production branches and tags, which
# includes building and testing on all supported platforms, and
# uploading the artifacts to S3.

# TODO:
#
# 1. Remove the use of "readies" completely.
# 2. Remove the use of all the scripts for anything and do everything
#    right here in the workflow.
# 3. Use the corresponding actions for the end goal: aws s3 upload
#    action. This also will remove the need for the installation of aws-cli.
#
# More info: jobs.steps.uses: docker://alpine:3.8 for docker images,
# To use the AWS CLI: https://hub.docker.com/r/amazon/aws-cli

on:
  # TODO REMOVE FROM HERE
  pull_request:
    paths-ignore:
      - '.circleci/**'
      - 'docs/**'
      - '*.md'
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+'
  push:
    paths-ignore:
      - '.circleci/**'
      - 'docs/**'
      - '*.md'
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-m[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      TAGGED: ${{ steps.set-tagged.outputs.TAGGED }}
      TAG: ${{ steps.set-git-info.outputs.TAG }}
      BRANCH: ${{ steps.set-git-info.outputs.BRANCH }}
      TAG_OR_BRANCH: ${{ steps.set-git-info.outputs.TAG }}${{ steps.set-git-info.outputs.BRANCH }}
    steps:
      - name: Set the branch and tag outputs
        id: set-git-info
        run: |
          export REF="${{ github.ref }}"
          export BRANCH_PATTERN="^refs/heads/(.*)$"
          export TAG_PATTERN="^refs/tags/(.*)$"

          if [[ $REF =~ $BRANCH_PATTERN ]]; then
            echo "BRANCH=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

          if [[ $REF =~ $TAG_PATTERN ]]; then
            echo "TAG=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi
      - name: Set the tagged flag
        id: set-tagged
        run: |
          # If this is a version tag, then set to false, meaning this
          # is not a production build.
          export REF="${{ github.ref }}"
          export PATTERN="refs/tags/v[0-9]+.*"
          if [[ $REF =~ $PATTERN ]]; then
            echo "This is a tagged build"
            echo "TAGGED=1" >> $GITHUB_OUTPUT
          else
            echo "This is not a tagged build"
            echo "TAGGED=0" >> $GITHUB_OUTPUT
          fi

  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Linter
        run: make lint

  bionic:
    runs-on: ubuntu-latest
    container: ${{ matrix.builder.image }}
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      TAGGED: ${{ needs.setup-environment.outputs.TAGGED }}
      VERSION: ${{ needs.setup-environment.outputs.TAG }}
      BRANCH: ${{ needs.setup-environment.outputs.BRANCH }}
      TAG_OR_BRANCH: ${{ needs.setup-environment.outputs.TAG_OR_BRANCH}}
    strategy:
      fail-fast: false
      matrix:
        redis-version: ["6.0.20", '6.2.16']
        builder: [
          {
            image: 'ubuntu:bionic',
            nick: 'bionic'
          },
        ]
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    needs: setup-environment
    steps:
      - name: Install build dependencies
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository ppa:git-core/ppa -y
          apt-get update
          apt-get install -y build-essential make autoconf automake libtool lcov git wget zlib1g-dev lsb-release libssl-dev openssl ca-certificates curl unzip
          wget https://cmake.org/files/v3.28/cmake-3.28.0.tar.gz
          tar -xzvf cmake-3.28.0.tar.gz
          cd cmake-3.28.0
          ./configure
          make -j `nproc`
          make install
          cd ..
          ln -s /usr/local/bin/cmake /usr/bin/cmake
          wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
          tar -xvf Python-3.9.6.tgz
          cd Python-3.9.6
          ./configure
          make -j `nproc`
          make altinstall
          cd ..
          rm /usr/bin/python3 && ln -s `which python3.9` /usr/bin/python3
          rm /usr/bin/lsb_release
          python3 --version
          make --version
          cmake --version
          python3 -m pip install --upgrade pip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
      - name: Checkout RedisBloom
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Python dependencies
        run: |
          python3 -m pip install -r tests/flow/requirements.txt
          python3 -m pip install -r .install/build_package_requirements.txt
      - name: Checkout Redis
        uses: actions/checkout@v3
        with:
          repository: 'redis/redis'
          ref: ${{ matrix.redis-version }}
          path: 'redis'
      - name: Build Redis
        run: |
          cd redis && make -j `nproc`
          echo "REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/redis/src" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
          redis-server --version
      - name: Build RedisBloom
        run: make -j `nproc`
      - name: Run tests
        run: make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
      - name: Pack module
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          make pack BRANCH=$TAG_OR_BRANCH SHOW=1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Upload artifacts to S3
        if: matrix.redis-version  == '6.0.20'
        run: |
          mkdir -p bin
          ln -s ~/workspace/artifacts bin/artifacts
          if [[ $TAGGED -eq 0 ]]; then
            make upload-artifacts SHOW=1 VERBOSE=1
          else
            make upload-release SHOW=1 VERBOSE=1
          fi
      - name: List artifacts
        run: |
          cd bin/artifacts
          du -ah --apparent-size *

  rocky-linux8:
    runs-on: ubuntu-latest
    container: ${{ matrix.builder.image }}
    env:
      TAGGED: ${{ needs.setup-environment.outputs.TAGGED }}
      VERSION: ${{ needs.setup-environment.outputs.TAG }}
      BRANCH: ${{ needs.setup-environment.outputs.BRANCH }}
      TAG_OR_BRANCH: ${{ needs.setup-environment.outputs.TAG_OR_BRANCH}}
    strategy:
      fail-fast: false
      matrix:
        redis-version: ["6.0.20", '6.2.16']
        builder: [{
            image: 'rockylinux:8',
            nick: 'rocky8'
          }
        ]
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    needs: setup-environment
    steps:
      - name: Install build dependencies
        run: |
          yum -y install epel-release
          yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
          yum -y install gcc make cmake3 git openssl-devel bzip2-devel libffi-devel zlib-devel wget scl-utils gcc-toolset-13 which
          yum groupinstall "Development Tools" -y
          . scl_source enable gcc-toolset-13 || true
          make --version
          gcc --version
          git --version
          wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
          tar -xvf Python-3.9.6.tgz
          cd Python-3.9.6
          ./configure
          make -j `nproc`
          make altinstall
          cd ..
          rm /usr/bin/python3 && ln -s `which python3.9` /usr/bin/python3
          cmake --version
          python3 --version
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Python dependencies
        run: |
          . scl_source enable gcc-toolset-13 || true
          python3 -m pip install -r tests/flow/requirements.txt
          python3 -m pip install -r .install/build_package_requirements.txt
      - name: Checkout Redis
        uses: actions/checkout@v3
        with:
          repository: 'redis/redis'
          ref: ${{ matrix.redis-version }}
          path: 'redis'
      - name: Build Redis
        run: |
          cd redis && make -j `nproc`
          echo "REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/redis/src" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
          redis-server --version
      - name: Build RedisBloom
        run: |
          . scl_source enable gcc-toolset-13 || true
          make -j `nproc`
      - name: Run tests
        run: |
          . scl_source enable gcc-toolset-13 || true
          make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
      - name: Pack module
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          make pack BRANCH=$TAG_OR_BRANCH SHOW=1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Upload artifacts to S3
        if: matrix.redis-version  == '6.0.20'
        run: |
          . scl_source enable gcc-toolset-13 || true
          mkdir -p bin
          ln -s ~/workspace/artifacts bin/artifacts
          if [[ $TAGGED -eq 0 ]]; then
            make upload-artifacts SHOW=1 VERBOSE=1
          else
            make upload-release SHOW=1 VERBOSE=1
          fi
      - name: List artifacts
        run: |
          cd bin/artifacts
          du -ah --apparent-size *

  centos7:
    runs-on: ubuntu-latest
    container: ${{ matrix.builder.image }}
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      TAGGED: ${{ needs.setup-environment.outputs.TAGGED }}
      VERSION: ${{ needs.setup-environment.outputs.TAG }}
      BRANCH: ${{ needs.setup-environment.outputs.BRANCH }}
      TAG_OR_BRANCH: ${{ needs.setup-environment.outputs.TAG_OR_BRANCH}}
    strategy:
      fail-fast: false
      matrix:
        redis-version: ["6.0.20", '6.2.16']
        builder: [
          {
            image: 'centos:7',
            nick: 'centos7'
          }
        ]
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    needs: setup-environment
    steps:
      - name: Install build dependencies
        run: |
          yum-config-manager --add-repo http://vault.centos.org/centos/7/sclo/x86_64/rh/
          rpm --import https://vault.centos.org/RPM-GPG-KEY-CentOS-7
          # http://mirror.centos.org/centos/7/ is deprecated, so we have to disable mirrorlists
          # and change the baseurl in the repo file to the working mirror (from mirror.centos.org to vault.centos.org)
          sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
          sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
          sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
          yum -y install epel-release
          yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
          yum -y install make cmake3 git python-pip openssl-devel bzip2-devel libffi-devel zlib-devel wget centos-release-scl scl-utils
          sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
          sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
          sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
          yum groups mark convert
          yum groupinstall "Development Tools" -y
          yum install -y devtoolset-11
          . scl_source enable devtoolset-11 || true
          make --version
          gcc --version
          git --version
          wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
          tar -xvf Python-3.9.6.tgz
          cd Python-3.9.6
          ./configure
          make -j `nproc`
          make altinstall
          cd ..
          rm /usr/bin/python3 && ln -s `which python3.9` /usr/bin/python3
          ln -s `which cmake3` /usr/bin/cmake
          python3 --version
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Python dependencies
        run: |
          scl enable devtoolset-11 bash
          python3 -m pip install -r tests/flow/requirements.txt
          python3 -m pip install -r .install/build_package_requirements.txt
      - name: Checkout Redis
        uses: actions/checkout@v3
        with:
          repository: 'redis/redis'
          ref: ${{ matrix.redis-version }}
          path: 'redis'
      - name: Build Redis
        run: |
          . scl_source enable devtoolset-11 || true
          cd redis && make -j `nproc`
          echo "REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/redis/src" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
          redis-server --version
      - name: Build RedisBloom
        run: |
          . scl_source enable devtoolset-11 || true
          make -j `nproc`
      - name: Run tests
        run: |
          . scl_source enable devtoolset-11 || true
          make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
      - name: Pack module
        run: |
          . scl_source enable devtoolset-11 || true
          git config --global --add safe.directory $GITHUB_WORKSPACE
          make pack BRANCH=$TAG_OR_BRANCH SHOW=1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Upload artifacts to S3
        if: matrix.redis-version  == '6.0.20'
        run: |
          . scl_source enable devtoolset-11 || true
          mkdir -p bin
          ln -s ~/workspace/artifacts bin/artifacts
          if [[ $TAGGED -eq 0 ]]; then
            make upload-artifacts SHOW=1 VERBOSE=1
          else
            make upload-release SHOW=1 VERBOSE=1
          fi

      - name: List artifacts
        run: |
          cd bin/artifacts
          du -ah --apparent-size *