name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init submodule
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: install redis
      run: |
        sudo add-apt-repository ppa:redislabs/redis
        sudo apt-get update
        sudo apt-get install redis
    - name: install deps
      run: |
        sudo ./deps/readies/bin/getpy3
        sudo ./system-setup.py
    - name: make test
      run: make test
